### PR TITLE
Update hotdogbot.py Please

### PR DESCRIPTION
**Pull request by IshaanAgarrwal**
I have added 2 decimal places. You are welcome, my friend.

### CODE REVIEW

**Comment by IshaanAgarrwal** [comment]
Hello thank you my friend. Of course accept request it is what you need my friend!

**Comment by IshaanAgarrwal** [comment]
Please my friend accept request I must get American project for resume!

**Comment by IshaanAgarrwal** [comment]
@edgymurphy420 Thank you my friend

**Comment by edgymurphy420** [comment]
@IshaanAgarrwal please add unit tests, rebase onto the latest master branch, and read through the contributing guidelines before creating a new PR

**Comment by IshaanAgarrwal** [comment]
Sir I do not see the contributing guidelines! Why did you not accept I added 2 decimal places! Please respond, my friend!

**Pull request closed without merging**
